// Single source of truth for mock data during UI scaffolding.
// Real backend will replace these arrays — keep shape aligned with types.ts.

import type {
  Appointment,
  AuditLogEntry,
  Client,
  EmailTemplate,
  Invoice,
  MembershipTier,
  Photo,
  ProjectTemplate,
  Staff,
  Vendor,
} from './types';

// ---------- Clients (with nested properties / projects / milestones) ----------

export const clients: Client[] = [
  {
    id: 'cli_harrington',
    name: 'Margaret Harrington',
    email: 'margaret@harringtonestate.com',
    phone: '(415) 555-0142',
    initials: 'MH',
    membershipTier: 'Platinum',
    assignedPM: 'David Hughes',
    memberSince: '2021-04-12',
    status: 'active',
    properties: [
      {
        id: 'prop_harr_pacific',
        clientId: 'cli_harrington',
        name: 'Pacific Heights Estate',
        address: '2430 Broadway',
        city: 'San Francisco, CA',
        sqft: 8400,
        yearBuilt: 1912,
        gateCode: '#4721',
        accessNotes: 'Side gate on Fillmore St. Dogs on property.',
        emergencyContact: 'Thomas Harrington — (415) 555-0109',
        projects: [
          {
            id: 'proj_harr_kitchen',
            propertyId: 'prop_harr_pacific',
            name: 'Chef Kitchen Remodel',
            type: 'remodel',
            status: 'in-progress',
            startDate: '2026-02-03',
            endDate: '2026-06-14',
            progress: 62,
            description:
              'Full chef-kitchen remodel — custom cabinetry, La Cornue range, marble counters, butler pantry build-out.',
            budget: {
              contract: 184000,
              changes: 12400,
              paid: 118000,
              remaining: 78400,
            },
            milestones: [
              {
                id: 'mile_harr_demo',
                projectId: 'proj_harr_kitchen',
                title: 'Demolition',
                category: 'Construction',
                dueDate: '2026-02-10',
                status: 'complete',
                vendor: 'Bayside Demolition',
              },
              {
                id: 'mile_harr_rough',
                projectId: 'proj_harr_kitchen',
                title: 'Rough plumbing and electrical',
                category: 'Construction',
                dueDate: '2026-03-08',
                status: 'complete',
                vendor: 'Northgate Mechanical',
              },
              {
                id: 'mile_harr_stone',
                projectId: 'proj_harr_kitchen',
                title: 'Countertop stone selection',
                category: 'Design',
                dueDate: '2026-04-22',
                status: 'awaiting-client',
                vendor: 'Artisan Stoneworks',
                questionType: 'single',
                questionBody:
                  'Which marble slab do you want us to pull from Artisan for the island counter? Samples were photographed on-site last Thursday.',
                options: [
                  'Calacatta Gold — Slab A',
                  'Calacatta Vagli — Slab C',
                  'Statuario — Slab F',
                ],
              },
              {
                id: 'mile_harr_cab',
                projectId: 'proj_harr_kitchen',
                title: 'Cabinetry install',
                category: 'Construction',
                dueDate: '2026-05-06',
                status: 'upcoming',
                vendor: 'Fine Line Cabinetry',
              },
              {
                id: 'mile_harr_final',
                projectId: 'proj_harr_kitchen',
                title: 'Final punch list',
                category: 'Closeout',
                dueDate: '2026-06-12',
                status: 'upcoming',
                vendor: 'Insight HM',
              },
            ],
            weeklyUpdates: [
              {
                date: '2026-04-10',
                author: 'David Hughes',
                note: 'Rough trades signed off. Tile backing goes up Monday — stone selection now gating the install schedule.',
                photoCount: 8,
              },
              {
                date: '2026-04-03',
                author: 'Priya Shah',
                note: 'Electrical final inspection passed. Butler pantry carpentry started.',
                photoCount: 5,
              },
            ],
            documents: [
              { name: 'Contract — signed.pdf', date: '2026-01-22', type: 'PDF' },
              { name: 'Change Order #2.pdf', date: '2026-03-14', type: 'PDF' },
              { name: 'Permit.pdf', date: '2026-01-30', type: 'PDF' },
            ],
          },
          {
            id: 'proj_harr_quarterly',
            propertyId: 'prop_harr_pacific',
            name: 'Q2 Preventive Maintenance',
            type: 'maintenance',
            status: 'in-progress',
            startDate: '2026-04-01',
            endDate: '2026-04-30',
            progress: 40,
            description:
              'Quarterly walkthrough covering HVAC, plumbing, exterior, and landscaping.',
            milestones: [
              {
                id: 'mile_harr_hvac',
                projectId: 'proj_harr_quarterly',
                title: 'HVAC filter + coil service',
                category: 'HVAC',
                dueDate: '2026-04-09',
                status: 'complete',
                vendor: 'Summit HVAC',
              },
              {
                id: 'mile_harr_gutter',
                projectId: 'proj_harr_quarterly',
                title: 'Gutter clearing + inspection',
                category: 'Exterior',
                dueDate: '2026-04-18',
                status: 'in-progress',
                vendor: 'Heights Roofing',
              },
              {
                id: 'mile_harr_irrigation',
                projectId: 'proj_harr_quarterly',
                title: 'Irrigation audit',
                category: 'Landscape',
                dueDate: '2026-04-24',
                status: 'upcoming',
                vendor: 'Bay Landscape Co.',
              },
            ],
          },
        ],
      },
      {
        id: 'prop_harr_tahoe',
        clientId: 'cli_harrington',
        name: 'Tahoe Lakefront',
        address: '782 Shoreline Drive',
        city: 'Tahoe City, CA',
        sqft: 5200,
        yearBuilt: 2004,
        accessNotes: 'Key in lockbox at main gate — code rotates quarterly.',
        projects: [
          {
            id: 'proj_harr_dock',
            propertyId: 'prop_harr_tahoe',
            name: 'Dock Refurbishment',
            type: 'remodel',
            status: 'planning',
            startDate: '2026-05-12',
            endDate: '2026-06-30',
            progress: 10,
            description: 'Re-deck the main dock, replace cleats, refinish boathouse trim.',
            milestones: [
              {
                id: 'mile_harr_dock_design',
                projectId: 'proj_harr_dock',
                title: 'Decking material approval',
                category: 'Design',
                dueDate: '2026-04-20',
                status: 'awaiting-client',
                vendor: 'Alpine Marine',
                questionType: 'approval',
                questionBody:
                  'Approve the Ipe hardwood quote ($18,400) or request us to re-bid with composite decking?',
                options: ['Approve Ipe quote', 'Re-bid with composite'],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'cli_okafor',
    name: 'Daniel Okafor',
    email: 'd.okafor@okaforgroup.com',
    phone: '(650) 555-0189',
    initials: 'DO',
    membershipTier: 'Gold',
    assignedPM: 'Priya Shah',
    memberSince: '2022-11-05',
    status: 'active',
    properties: [
      {
        id: 'prop_okafor_atherton',
        clientId: 'cli_okafor',
        name: 'Atherton Residence',
        address: '14 Selby Lane',
        city: 'Atherton, CA',
        sqft: 6100,
        yearBuilt: 1998,
        gateCode: '#0214',
        projects: [
          {
            id: 'proj_okafor_pool',
            propertyId: 'prop_okafor_atherton',
            name: 'Pool House Refresh',
            type: 'remodel',
            status: 'in-progress',
            startDate: '2026-03-10',
            endDate: '2026-05-22',
            progress: 48,
            description:
              'Repaint pool house, replace pool-adjacent sliders, new pergola staining, upgrade outdoor lighting.',
            budget: {
              contract: 62500,
              changes: 3200,
              paid: 30000,
              remaining: 35700,
            },
            milestones: [
              {
                id: 'mile_okafor_paint',
                projectId: 'proj_okafor_pool',
                title: 'Exterior paint color confirmation',
                category: 'Design',
                dueDate: '2026-04-15',
                status: 'awaiting-client',
                vendor: 'Benjamin Paints',
                questionType: 'single',
                questionBody: 'Confirm exterior trim color (three Benjamin Moore options).',
                options: ['Chantilly Lace', 'Simply White', 'White Dove'],
              },
              {
                id: 'mile_okafor_pergola',
                projectId: 'proj_okafor_pool',
                title: 'Pergola refinish',
                category: 'Carpentry',
                dueDate: '2026-04-28',
                status: 'upcoming',
                vendor: 'Pacific Woodworks',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'cli_vanholt',
    name: 'Elena Van Holt',
    email: 'elena@vanholt.io',
    phone: '(415) 555-0171',
    initials: 'EV',
    membershipTier: 'Platinum',
    assignedPM: 'David Hughes',
    memberSince: '2020-08-30',
    status: 'active',
    properties: [
      {
        id: 'prop_vanholt_presidio',
        clientId: 'cli_vanholt',
        name: 'Presidio Heights Townhome',
        address: '3102 Washington St',
        city: 'San Francisco, CA',
        sqft: 4800,
        yearBuilt: 1925,
        projects: [
          {
            id: 'proj_vanholt_roof',
            propertyId: 'prop_vanholt_presidio',
            name: 'Roof Replacement + Skylights',
            type: 'remodel',
            status: 'in-progress',
            startDate: '2026-03-24',
            endDate: '2026-05-02',
            progress: 72,
            description: 'Full tear-off, new standing seam, two skylight retrofits.',
            milestones: [
              {
                id: 'mile_vanholt_teardown',
                projectId: 'proj_vanholt_roof',
                title: 'Tear-off complete',
                category: 'Roofing',
                dueDate: '2026-03-28',
                status: 'complete',
                vendor: 'Heights Roofing',
              },
              {
                id: 'mile_vanholt_standing',
                projectId: 'proj_vanholt_roof',
                title: 'Standing seam install',
                category: 'Roofing',
                dueDate: '2026-04-18',
                status: 'in-progress',
                vendor: 'Heights Roofing',
              },
              {
                id: 'mile_vanholt_skylight',
                projectId: 'proj_vanholt_roof',
                title: 'Skylight retrofit',
                category: 'Roofing',
                dueDate: '2026-04-25',
                status: 'upcoming',
                vendor: 'Daylight Skylights',
              },
            ],
          },
        ],
      },
    ],
  },
];

// ---------- Appointments ----------

export const appointments: Appointment[] = [
  {
    id: 'appt_1',
    propertyId: 'prop_harr_pacific',
    projectId: 'proj_harr_kitchen',
    title: 'Tile backer install walkthrough',
    vendor: 'Fine Line Cabinetry',
    date: '2026-04-16',
    startTime: '09:00',
    endTime: '10:30',
    status: 'scheduled',
    davidOnSite: true,
    scopeOfWork: 'Verify blocking for upper cabinets; confirm outlet positions against elevation.',
    assignedPM: 'David Hughes',
  },
  {
    id: 'appt_2',
    propertyId: 'prop_vanholt_presidio',
    projectId: 'proj_vanholt_roof',
    title: 'Standing seam panel delivery',
    vendor: 'Heights Roofing',
    date: '2026-04-16',
    startTime: '11:00',
    endTime: '12:00',
    status: 'scheduled',
    davidOnSite: false,
    scopeOfWork: 'Receive truck, verify panel count against PO, stage on south side.',
    assignedPM: 'David Hughes',
  },
  {
    id: 'appt_3',
    propertyId: 'prop_okafor_atherton',
    projectId: 'proj_okafor_pool',
    title: 'Paint sample review with client',
    vendor: 'Benjamin Paints',
    date: '2026-04-16',
    startTime: '15:00',
    endTime: '15:45',
    status: 'scheduled',
    davidOnSite: true,
    scopeOfWork: 'Walk three exterior trim samples with Daniel. Confirm final pick.',
    assignedPM: 'Priya Shah',
  },
  {
    id: 'appt_4',
    propertyId: 'prop_harr_pacific',
    projectId: 'proj_harr_quarterly',
    title: 'Gutter clearing',
    vendor: 'Heights Roofing',
    date: '2026-04-18',
    startTime: '08:30',
    endTime: '11:00',
    status: 'scheduled',
    davidOnSite: false,
    scopeOfWork: 'Clear gutters, photograph condition, flag any sagging sections.',
    assignedPM: 'David Hughes',
  },
];

// ---------- Photos ----------

export const photos: Photo[] = [
  {
    id: 'photo_1',
    propertyId: 'prop_harr_pacific',
    projectId: 'proj_harr_kitchen',
    uploadedBy: 'David Hughes',
    uploadedAt: '2026-04-15T16:22:00-07:00',
    tag: 'during',
    category: 'Construction progress',
    caption: 'Rough plumbing signed off, ready for backer.',
    status: 'pending',
    color: '#D7C9AE',
  },
  {
    id: 'photo_2',
    propertyId: 'prop_vanholt_presidio',
    projectId: 'proj_vanholt_roof',
    uploadedBy: 'Marco Lopez',
    uploadedAt: '2026-04-15T11:04:00-07:00',
    tag: 'during',
    category: 'Roofing',
    caption: 'Underlayment complete on south face.',
    status: 'pending',
    color: '#B9C7C9',
  },
  {
    id: 'photo_3',
    propertyId: 'prop_okafor_atherton',
    projectId: 'proj_okafor_pool',
    uploadedBy: 'Priya Shah',
    uploadedAt: '2026-04-14T17:41:00-07:00',
    tag: 'before',
    category: 'Exterior',
    caption: 'Original pergola staining — badly faded on west beam.',
    status: 'pending',
    color: '#C9B89A',
  },
  {
    id: 'photo_4',
    propertyId: 'prop_harr_pacific',
    projectId: 'proj_harr_kitchen',
    uploadedBy: 'David Hughes',
    uploadedAt: '2026-04-12T10:08:00-07:00',
    tag: 'before',
    category: 'Construction progress',
    caption: 'Original cabinetry prior to demolition.',
    status: 'categorized',
    color: '#C4B5A0',
  },
];

// ---------- Invoices ----------

export const invoices: Invoice[] = [
  {
    id: 'inv_1',
    clientId: 'cli_harrington',
    clientName: 'Margaret Harrington',
    propertyId: 'prop_harr_pacific',
    propertyName: 'Pacific Heights Estate',
    projectId: 'proj_harr_kitchen',
    projectName: 'Chef Kitchen Remodel',
    invoiceNumber: 'IHM-2026-0142',
    description: 'Progress billing — cabinetry deposit',
    amount: 42500,
    invoiceDate: '2026-04-01',
    dueDate: '2026-04-22',
    status: 'unpaid',
  },
  {
    id: 'inv_2',
    clientId: 'cli_okafor',
    clientName: 'Daniel Okafor',
    propertyId: 'prop_okafor_atherton',
    propertyName: 'Atherton Residence',
    projectId: 'proj_okafor_pool',
    projectName: 'Pool House Refresh',
    invoiceNumber: 'IHM-2026-0138',
    description: 'Carpentry labor — weeks 3–4',
    amount: 8750,
    invoiceDate: '2026-03-28',
    dueDate: '2026-04-18',
    status: 'partial',
  },
  {
    id: 'inv_3',
    clientId: 'cli_vanholt',
    clientName: 'Elena Van Holt',
    propertyId: 'prop_vanholt_presidio',
    propertyName: 'Presidio Heights Townhome',
    projectId: 'proj_vanholt_roof',
    projectName: 'Roof Replacement + Skylights',
    invoiceNumber: 'IHM-2026-0130',
    description: 'Tear-off + underlayment',
    amount: 18200,
    invoiceDate: '2026-03-20',
    dueDate: '2026-04-05',
    status: 'paid',
  },
  {
    id: 'inv_4',
    clientId: 'cli_harrington',
    clientName: 'Margaret Harrington',
    propertyId: 'prop_harr_pacific',
    propertyName: 'Pacific Heights Estate',
    projectId: 'proj_harr_quarterly',
    projectName: 'Q2 Preventive Maintenance',
    invoiceNumber: 'IHM-2026-0119',
    description: 'Quarterly maintenance membership',
    amount: 4500,
    invoiceDate: '2026-04-01',
    dueDate: '2026-04-30',
    status: 'unpaid',
  },
];

// ---------- Vendors ----------

export const vendors: Vendor[] = [
  {
    id: 'ven_summit',
    name: 'Summit HVAC',
    category: 'HVAC',
    phone: '(415) 555-0220',
    email: 'dispatch@summithvac.com',
    active: true,
    rating: 4.8,
    jobsCompleted: 38,
    notes: 'Preferred for Heights clients. Ask for Tomas.',
  },
  {
    id: 'ven_heights',
    name: 'Heights Roofing',
    category: 'Roofing',
    phone: '(415) 555-0248',
    email: 'jobs@heightsroofing.com',
    active: true,
    rating: 4.9,
    jobsCompleted: 27,
  },
  {
    id: 'ven_fineline',
    name: 'Fine Line Cabinetry',
    category: 'Cabinetry',
    phone: '(650) 555-0109',
    email: 'shop@finelinecab.com',
    active: true,
    rating: 4.7,
    jobsCompleted: 14,
  },
  {
    id: 'ven_artisan',
    name: 'Artisan Stoneworks',
    category: 'Stone / Counters',
    phone: '(510) 555-0155',
    email: 'sales@artisanstone.co',
    active: true,
    rating: 4.6,
    jobsCompleted: 22,
  },
  {
    id: 'ven_pacific',
    name: 'Pacific Woodworks',
    category: 'Carpentry',
    phone: '(415) 555-0293',
    email: 'hello@pacificwood.co',
    active: false,
    rating: 4.2,
    jobsCompleted: 6,
    notes: 'Paused pending insurance renewal.',
  },
];

// ---------- Staff ----------

export const staff: Staff[] = [
  {
    id: 'staff_david',
    name: 'David Hughes',
    role: 'Owner / Lead PM',
    email: 'david@insighthm.com',
    phone: '(415) 555-0101',
    initials: 'DH',
    clientsAssigned: 12,
    status: 'active',
  },
  {
    id: 'staff_priya',
    name: 'Priya Shah',
    role: 'Project Manager',
    email: 'priya@insighthm.com',
    phone: '(415) 555-0122',
    initials: 'PS',
    clientsAssigned: 7,
    status: 'active',
  },
  {
    id: 'staff_marco',
    name: 'Marco Lopez',
    role: 'Field Supervisor',
    email: 'marco@insighthm.com',
    phone: '(415) 555-0165',
    initials: 'ML',
    clientsAssigned: 0,
    status: 'active',
  },
  {
    id: 'staff_jade',
    name: 'Jade Nguyen',
    role: 'Client Coordinator',
    email: 'jade@insighthm.com',
    phone: '(415) 555-0188',
    initials: 'JN',
    clientsAssigned: 4,
    status: 'pending',
  },
];

// ---------- Project templates ----------

export const templates: ProjectTemplate[] = [
  {
    id: 'tmpl_kitchen',
    name: 'Chef Kitchen Remodel',
    type: 'remodel',
    description: 'Full kitchen remodel — demo, rough trades, cabinetry, counters, finish.',
    duration: '14–18 weeks',
    milestones: [
      'Design approval',
      'Demolition',
      'Rough plumbing and electrical',
      'Countertop stone selection',
      'Cabinetry install',
      'Appliance install',
      'Final punch list',
    ],
  },
  {
    id: 'tmpl_quarterly',
    name: 'Quarterly Preventive Maintenance',
    type: 'maintenance',
    description: 'Standard quarterly touchpoint for all membership clients.',
    duration: '4 weeks',
    milestones: [
      'HVAC service',
      'Plumbing walkthrough',
      'Gutter and exterior',
      'Irrigation audit',
      'Quarterly report',
    ],
  },
  {
    id: 'tmpl_roof',
    name: 'Roof Replacement',
    type: 'remodel',
    description: 'Standard tear-off + replacement package.',
    duration: '5–7 weeks',
    milestones: [
      'Tear-off',
      'Underlayment',
      'Panel / shingle install',
      'Flashing and penetrations',
      'Final inspection',
    ],
  },
];

// ---------- Membership tiers ----------

export const membershipTiers: MembershipTier[] = [
  {
    id: 'tier_platinum',
    name: 'Platinum',
    annualPrice: 24000,
    description: 'White-glove — weekly walkthroughs, priority response, bundled remodels.',
    clientCount: 4,
  },
  {
    id: 'tier_gold',
    name: 'Gold',
    annualPrice: 12000,
    description: 'Monthly walkthroughs, quarterly deep service, priority scheduling.',
    clientCount: 9,
  },
  {
    id: 'tier_silver',
    name: 'Silver',
    annualPrice: 6000,
    description: 'Quarterly walkthroughs and standard service discount.',
    clientCount: 16,
  },
];

// ---------- Audit log ----------

export const auditLog: AuditLogEntry[] = [
  {
    id: 'aud_1',
    actor: 'David Hughes',
    action: 'Uploaded invoice',
    target: 'IHM-2026-0142',
    client: 'Margaret Harrington',
    time: '2026-04-15T17:22:00-07:00',
  },
  {
    id: 'aud_2',
    actor: 'Priya Shah',
    action: 'Categorized 6 photos',
    target: 'Pool House Refresh',
    client: 'Daniel Okafor',
    time: '2026-04-15T15:08:00-07:00',
  },
  {
    id: 'aud_3',
    actor: 'David Hughes',
    action: 'Posted weekly update',
    target: 'Chef Kitchen Remodel',
    client: 'Margaret Harrington',
    time: '2026-04-10T11:40:00-07:00',
  },
  {
    id: 'aud_4',
    actor: 'Jade Nguyen',
    action: 'Scheduled appointment',
    target: 'Tile backer walkthrough',
    client: 'Margaret Harrington',
    time: '2026-04-14T09:12:00-07:00',
  },
];

// ---------- Email templates ----------

export const emailTemplates: EmailTemplate[] = [
  {
    id: 'tmpl_welcome',
    name: 'New client welcome',
    subject: 'Welcome to Insight Home Maintenance',
    lastEdited: '2026-02-14',
  },
  {
    id: 'tmpl_decision',
    name: 'Decision request',
    subject: 'Quick decision needed on {project_name}',
    lastEdited: '2026-03-02',
  },
  {
    id: 'tmpl_weekly',
    name: 'Weekly project update',
    subject: 'This week at {property_name}',
    lastEdited: '2026-03-21',
  },
  {
    id: 'tmpl_invoice',
    name: 'Invoice posted',
    subject: 'New invoice from Insight HM',
    lastEdited: '2026-02-28',
  },
];
