-- Data-only migration (no schema change). Seed the auth-email templates we now
-- send ourselves via Resend instead of letting Supabase send its unbranded
-- defaults. Same shape as the templates seeded in 0014: teal (#1B4F5A) header
-- with the public PNG logo, gold (#C8963E) CTA button, {{cta_url}} carries the
-- link generated by auth.admin.generateLink().
--
--   staff_invite   — non-client invites (admin / field_staff); client invites
--                    keep using welcome_client.
--   password_reset — recovery link (replaces Supabase's recovery email).
--   magic_link     — passwordless sign-in link (replaces Supabase's magic-link
--                    email).

INSERT INTO "email_templates" ("name", "key", "subject", "body", "body_html", "variables", "enabled") VALUES
(
  'Staff invite',
  'staff_invite',
  'Set up your {{firm_name}} account',
  E'Hi {{user_name}},\n\nYou''ve been added to the {{firm_name}} team console. Set your password to activate your account:\n{{cta_url}}\n\nThis one link sets your password and signs you in.\n\n— {{firm_name}}',
  E'<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Inter,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto"><tr><td style="background:#1B4F5A;padding:24px 32px;text-align:center"><img src="{{logo_url}}" alt="{{firm_name}}" height="28" style="height:28px" /></td></tr><tr><td style="padding:32px"><h2 style="margin:0 0 16px;color:#1A1F1E;font-size:20px">Set up your account</h2><p style="color:#3C4543;font-size:15px;line-height:1.6;margin:0 0 16px">Hi {{user_name}},</p><p style="color:#3C4543;font-size:15px;line-height:1.6;margin:0 0 24px">You''ve been added to the {{firm_name}} team console. Set your password to activate your account.</p><table cellpadding="0" cellspacing="0"><tr><td style="background:#C8963E;border-radius:8px;padding:12px 24px"><a href="{{cta_url}}" style="color:#fff;text-decoration:none;font-weight:600;font-size:14px">Set your password</a></td></tr></table><p style="color:#6B7370;font-size:13px;margin:24px 0 0">This link sets your password and signs you in.<br/>— {{firm_name}}</p></td></tr></table>',
  '["user_name","cta_url","firm_name","logo_url"]'::jsonb,
  true
),
(
  'Password reset',
  'password_reset',
  'Reset your {{firm_name}} password',
  E'Hi,\n\nWe received a request to reset the password for your {{firm_name}} account. Choose a new one here:\n{{cta_url}}\n\nIf you didn''t request this, you can safely ignore this email — your password won''t change.\n\n— {{firm_name}}',
  E'<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Inter,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto"><tr><td style="background:#1B4F5A;padding:24px 32px;text-align:center"><img src="{{logo_url}}" alt="{{firm_name}}" height="28" style="height:28px" /></td></tr><tr><td style="padding:32px"><h2 style="margin:0 0 16px;color:#1A1F1E;font-size:20px">Reset your password</h2><p style="color:#3C4543;font-size:15px;line-height:1.6;margin:0 0 24px">We received a request to reset the password for your {{firm_name}} account. Choose a new one below.</p><table cellpadding="0" cellspacing="0"><tr><td style="background:#C8963E;border-radius:8px;padding:12px 24px"><a href="{{cta_url}}" style="color:#fff;text-decoration:none;font-weight:600;font-size:14px">Reset password</a></td></tr></table><p style="color:#6B7370;font-size:13px;margin:24px 0 0">If you didn''t request this, you can safely ignore this email — your password won''t change.<br/>— {{firm_name}}</p></td></tr></table>',
  '["cta_url","firm_name","logo_url"]'::jsonb,
  true
),
(
  'Magic link sign-in',
  'magic_link',
  'Your {{firm_name}} sign-in link',
  E'Hi,\n\nHere''s your secure sign-in link for {{firm_name}}:\n{{cta_url}}\n\nThis link signs you in without a password. If you didn''t request it, you can safely ignore this email.\n\n— {{firm_name}}',
  E'<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Inter,Helvetica,Arial,sans-serif;max-width:600px;margin:0 auto"><tr><td style="background:#1B4F5A;padding:24px 32px;text-align:center"><img src="{{logo_url}}" alt="{{firm_name}}" height="28" style="height:28px" /></td></tr><tr><td style="padding:32px"><h2 style="margin:0 0 16px;color:#1A1F1E;font-size:20px">Sign in to {{firm_name}}</h2><p style="color:#3C4543;font-size:15px;line-height:1.6;margin:0 0 24px">Use the secure link below to sign in — no password needed.</p><table cellpadding="0" cellspacing="0"><tr><td style="background:#C8963E;border-radius:8px;padding:12px 24px"><a href="{{cta_url}}" style="color:#fff;text-decoration:none;font-weight:600;font-size:14px">Sign in</a></td></tr></table><p style="color:#6B7370;font-size:13px;margin:24px 0 0">If you didn''t request this link, you can safely ignore this email.<br/>— {{firm_name}}</p></td></tr></table>',
  '["cta_url","firm_name","logo_url"]'::jsonb,
  true
);
